### ISSUE TITLE
Multiple index.md files in a working group cause multiple working group listings

### ISSUE THREAD

**Issue by schickm** [EI2030/EI2030#7]
**Expected Behavior**

Each Working Group is listed once on the main page

**Actual Behavior**

Driving E-ink Displays is listed 3 times

<img width="295" alt="image" src="https://user-images.githubusercontent.com/197222/118282034-b461f980-b482-11eb-9ad9-b27b96ea9291.png">

**Background**

The list of working groups on the main page is not actually that.  Instead it's a list of "all WorkingGroupPages that have a file of `index.md`".  See this query here:
https://github.com/EI2030/EI2030/blob/main/src/pages/index.js#L8

So, when @alex-a-soto put together the example of multiple subdirectories within a working group repo - and there were multiple `index.md` files - naturally the main page got a little wacky.

Fixing this might require changing up how pages are generated.  We might need to move away from using the [File System Route API](File System Route API), and instead go to the old way of just using [createPages](https://www.gatsbyjs.com/docs/reference/config-files/gatsby-node/#createPages).  While the former is fun and new, and conceptually would require less code, in practice is seems like using the later will give us more control.  Furthermore, the [File System Route API seems to have some clear shortcomings](https://github.com/gatsbyjs/gatsby/discussions/26375#discussioncomment-738566) when working with data that is relationship heavy.  However....I think `createPages` might have to deal with the same sort of shortcomings as well 🤷‍♂️

**Comment by alex-a-soto** [comment]
@schickm Thank you for creating this issue. How about temporarily we create conventions related to the creation of directories and files? :clipboard: 

A related idea is to use [HackerMD](https://hackmd.io/), a collaborative markdown editor. We can create templates, collaborate on a document, and have Github integration to push or pull from a repository.

For example, a working group repository should only have one index.md

Are there other benefits or quirks that would be addressed by changing how the pages are generated? :card_file_box: 

Open to feedback, suggestions, thoughts. :thinking:

**Comment by schickm** [comment]
I don't think it's necessary to create those restrictions of "only a single index.md", I just need to adjust the graphql query that's generating the pages, it's a quick fix.  My existing query is a little naive, I'm just checking for a file named "index.md" and not verifying that it's located at the top level of the "website/" directory.

We could incorporate something like HackerMD if you'd like.  But it's not clear to me how that'll address any of the prior issues.  They seem to offer an enhanced editing experience, and then [some really nice advanced markdown rendering](https://hackmd.io/@codimd/extra-supported-syntax), but I think we'd miss out on all that fancy rendering if we're just syncing the raw MD files over onto Github, and then processing them with our Gatsby site....

I guess my question should be a broader one of "What problem do you see HackerMD solving?"  It's not clear to me that it's the right way to solve "the website renders too many index.md files" 😆

**Comment by alex-a-soto** [comment]
@schickm, Ok, I was under the assumption that to address the problem of multiple subdirectories with multiple index.md would require a more significant overhaul rather than adjusting the graphql query. That's why I mentioned the idea of only creating a single index.md

You are correct. HackerMD wasn't directly related to the issue :sweat_smile: I was exploring using HackerMD to address how people can collaborate in real time and then publish it on the site :thinking: In the end, it shouldn't matter which tool is used to create the markdown files.
